### ISSUE TITLE
Not updating config

### ISSUE THREAD

**Issue by DGovender** [deadc0de6/dotdrop#103]
Hi, didn't know where else to ask this.
I currently have two configs: Config A and Config B.
I setup Config A with github (submodule method) and by importing my config files which only consist of the .i3 folder in the home directory.
I then cloned the dotfiles folder onto my secondary pc and created the profile Config B.
I then imported the i3 folder but it doesn't save this config at all.
Do I need to add something to the config.yaml to be able to use the jinja templating system?
Also when I type in dotdrop install Config A on the secondary computer, it says that there is no dotfiles to be installed for this profile on the secondary computer

**Comment by deadc0de6** [comment]
Hello, here is the right place to ask ;-)

I'm taking your attempt with dotdrop is this: <https://github.com/DGovender/dotfiles>

It looks good. I guess that when you run `install` on your secondary pc it says something like `[WARN] no dotfile to install for this profile ("XXX")` (where *XXX* is your hostname). This is because dotdrop works with profile and currently you have only one profile in your config file: *darien*.

So either your use the same profile on your second host (either by providing `--profile=darien` on the command line or by defining the env variable `DOTDROP_PROFILE="darien"`) or you create a new profile in the `config.yaml`:
```yaml
...
profiles:
  darien:
    dotfiles:
    - d_i3
  XXX:
    dotfiles:
    - d_i3
```

Then you can edit some files (for example [i3 config](https://github.com/DGovender/dotfiles/blob/master/dotfiles/i3/config)) and add some templating directives.

For more, check the [templating doc](https://github.com/deadc0de6/dotdrop/wiki/templating) and the [example](https://github.com/deadc0de6/dotdrop#example).

Feel free to ask your questions here if you are having any issue or if anything is unclear!

**Comment by DGovender** [comment]
Hi.

Thank you for your assistance. I have got the templating working because I now understand that only one file is stored in the dotfiles folder for i3/config.
Just want to make sure I understand this right: When editing my config that's been imported I should edit the files in the dotfiles folder and install it for the changes to reflect?

**Comment by deadc0de6** [comment]
Yes, before installing dotfiles you need to go through a *configuration phase* where you edit your `config.yaml` to define which dotfiles is installed with which profile (and add actions, transformations and other stuff) and also edit your dotfiles within dotdrop (in the *dotpath* dir) to add any needed jinja2 directives.

**Comment by deadc0de6** [comment]
If that helps, you can have a look on how other people are using dotdrop by simply searching for configs on github: <https://github.com/search?q=filename%3Aconfig.yaml+dotdrop&type=Code>

**Comment by deadc0de6** [comment]
I have updated the [getting started](https://github.com/deadc0de6/dotdrop#getting-started) doc. I hope it now better shows how to proceed when starting fresh with dotdrop. 
Feel free to let me know what you think or if it's missing any key information.
Thanks!
