### ISSUE TITLE
[feature] ability to import entire profile

### ISSUE THREAD

**Issue by deadc0de6** [deadc0de6/dotdrop#113]
Add the ability to import entire profile in the same idea as `import_variables`

See original request here: #112

**Comment by weilbith** [comment]
Having a `import_profiles` next to `import_variables` would be nice. I'm finally about to switch all my dotfiles to work with Dotdrop. This is quite a lot even if I'm using all exports which are supported right now. With the future global defaults for linking etc it will become even less with one line less per dotfile. Nevertheless I will end up with over 50 of such entries a at least 5 lines of properties (`key`, `action` +1, `dst`, 'src [, `link`]). Which makes without any empty lines already 250 lines. And this is the minimum for me. So it will become a messy file even with (dyn)variables and profiles exported.
An also very easy to go for approach with the identical solution would be to have `import_variables`, `import_profiles` and `import_actions`. Additionally the usage of globs for paths would be awesome. This would reduce the import of mainly `profiles` even more. So the user  could name all his profiles with a prefix `profile_*.yaml` or as you suggest having a dedicated folder `profiles.d/*`.
Going further on the hunt to separate a huge messy file as good as possible, introducing also `import_dotfiles` seems to be useless. After the above options, the `config.yaml` file is most likely only the global `config` section with all the imports and the `dotfiles` section afterwards. But actually all other exported files together are probably even less then only the `dotfiles` section. So what could we do. Easy to go would the split into multiple dotfiles which become imported, as for the other options is possible as well. Using globs again this would be quite nice. But how does it looks like now? I would assume it will be not very clean to read or find. But maybe this is just me and my approach to use this.
Because next to my different hosts (which are only two...) I split my dotfiles into groups like organization stuff (all for mail [mutt, isync, msmtp, notmuch, mailcap, ...], calendar, contacts), for data management (git, ranger, bashmount, udisk, ...), shell is a whole lot of stuff, networking, etc pp. Each is one profile, which I can export to its dedicated file and include into the "mail" profiles. So right now all information are wide spread. This is nice to get a better overview and find things fast. But the chain of profile -> include -> import -> dotfile -> action -> import -> variable -> import is quieeeete long. But to be honest I've no better idea.

Yeah, this are just my thoughts. Hopefully something of this make any sense  xD

**Comment by weilbith** [comment]
As you can maybe think of, my vision is to have a full setup of my distro afterwards. That's also why I use this docker image to test. So the dream is to install the distro on a PC, install dotdrop and pull my repository, run dotdrop on all or specific profiles and all is set up, ready to work. Okay, I must sync my private data from my cloud server, but this could run over night. This is also why abuse actions so much for installing etc. 
I write this just that you get an idea what this crazy guy is actually doing. xD

**Comment by deadc0de6** [comment]
These are all good idea, what I would suggest is to go step by step. Starting with the ability to `import_profiles` and `import_actions`. That would already help a bit.

A good way is to create profile per topic and import those, for example

`profiles.d/weechat.yaml`
```yaml
  weechat:
    dotfiles:
    - f_weechatbuffers
    - f_weechat.conf
```

`config.yaml`
```yaml
  profiles:
    myhost:
      include:
      - weechat
```

Of couse one of the big disadvantage of splitting the config is for searching and finding what is where but this is another story.

Yeah I see where you're going with that and find that very interesting, I'm happy to help if I can!

**Comment by weilbith** [comment]
Having `import_profiles` and `import_actions` sound great. I think this fits also pretty wel into the current schema!

**Comment by deadc0de6** [comment]
I made an attempt at importing external actions from file in the branch `extactions`.

It can be used like this for example:
```yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
  import_actions:
  - actions.yaml
...
```

**Comment by weilbith** [comment]
Feature is working.
I'm a bid confused, because I get this error message (dotfile get installed anyway):
`[ERR] dotfile points to itself: /tmp/test_dotfile`
I checked it, but internal dotfile is no link. I guess this is not part of the recent commits for the feature, but can you understand why this error occurs? :thinking:

**Comment by deadc0de6** [comment]
I'm unable to reproduce the `dotfile points to itself` error, can you provide me with your workflow and the debug logs (with `-V --verbose`)?

**Comment by weilbith** [comment]
Hmm I was stupid and deleted the test directory. I will open an issue if I have a 100% reproducable flow.

I don't want to abuse this issue, but also think a new issue is probably too much.
I've defined some environment variables in a file. I source this file before executing dotdrop. I can confirm that the variable is defined in the shell now. But if I try to access the variable within the `config.yaml` file, I get an empty result always, leaving me with errors that permissions are denied to install a dotfile to the root directory.

`env`:
```sh
XDG_CONFIG_HOME=$HOME/.config
```

`config.yaml`:
```yaml
dotfiles:
   test:
      src: test
      dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/test'
```

Flow:
```sh
> echo $XDG_CONFIG_HOME

> source ./env
> echo $XDG_CONFIG_HOME
/home/user/.config
> dotfile install
...
PermissionError: [Errno 13] Permission denied: '/home/user/dotfiles/dotfiles/test' -> '/test'
```

What am I doing wrong? :thinking:

**Comment by deadc0de6** [comment]
@weilbith I'm sorry but I received a notification with a comment from you but it was deleted it seems, have you been able to solve your issue?

**Comment by weilbith** [comment]
Oh. Could be :joy:
Unfortunately I deleted my test directory with this. So I close this and in case I have it again with a 100% reproduceable workflow.
Thanks for you time!

**Comment by deadc0de6** [comment]
No problem, let me know if you encounter that issue again.

**Comment by deadc0de6** [comment]
I merged the branch into master and `import_actions` is now available in the master branch.
The related doc is [here](https://github.com/deadc0de6/dotdrop/wiki/config#import-actions-from-file)

Next step: importing profiles

**Comment by davla** [comment]
It took me a while to figure out, but I would need this too.

How far are you on this? I can see no branch with a promising name or anything like that. I ask as I'll be able to contribute myself in a couple of weeks, so any pointer to where I can start looking would be appreciated. :smiley:

**Comment by deadc0de6** [comment]
@davla sorry haven't started this yet. Didn't get the time yet.

If you're able to help, that'd be awesome. 

One of the big problem with external profiles is on the `import` part as importing dotfiles is *patching* the config file to add the dotfiles to each profiles. Currently this is all flat in a file and thus quite easy but with external profile files, the config needs to know where to patch (in which file). A big part is on the `config.py` source file. TBH I think It might need some rework to be able to cleanly do this.

This doable, just needs time.

**Comment by weilbith** [comment]
@deadc0de6 the most recent version of the PyPI package is `v0.23.1` and has been build on the 20.03. This is before 228524bdf3881219021c7d46347d2af5dd7bc24f has been merged to `master` (28.03.). But [here](https://github.com/deadc0de6/dotdrop/issues/110#issuecomment-480698547) (08.04.) you stated what a new version has been build.
The problem is that the `import_actions` is not working for me when using the python module. There is no error on the `import_actions` key property itself (doesn't unknown properties lead to an exception? :thinking:) but all actions are stated to be unknown.

**Comment by deadc0de6** [comment]
@weilbith this new feature hasn't been released on pypi yet. I'll do that tonight.

**Comment by weilbith** [comment]
Ah okay. Then this makes sense. :D
The fix for #112 isn't also, so I will just wait.

**Comment by deadc0de6** [comment]
@weilbith version released

**Comment by davla** [comment]
> @davla sorry haven't started this yet. Didn't get the time yet.
> 
> If you're able to help, that'd be awesome.
> 
> One of the big problem with external profiles is on the `import` part as importing dotfiles is _patching_ the config file to add the dotfiles to each profiles. Currently this is all flat in a file and thus quite easy but with external profile files, the config needs to know where to patch (in which file). A big part is on the `config.py` source file. TBH I think It might need some rework to be able to cleanly do this.
> 
> This doable, just needs time.

I see your _patching_, you mean the method `_get_included_dotfiles`, don't you? As for the rest, I'm still unaware of how the `Cfg` class is used, so I'm not sure. But I assume you meant something like creating a `Profile` class and recursively parsing the included profiles. Sounds exactly like you said, manageable but time consuming.

**Comment by deadc0de6** [comment]
No by patching I mean the [*new* method](https://github.com/deadc0de6/dotdrop/blob/master/dotdrop/config.py#L767) in `config.py`. It creates the new dotfile, adds it to the profile in the yaml dictionary and saves the new config file. 

The tricky part is that there are two *layers* to the config, the yaml file itself (`config.yaml`) and its *representation* in dotdrop (using dicts and lists for example to *attach* dotfiles to profile). With one single file it was easy but once we have multiple, the location where each dotfile/profile comes from need also to be stored/known to make sure to patch the correct file. It is not difficult just error-prone and time consuming.

I'll have to rework the way these elements are represented in dotdrop as this will be useful for #47 too.

**Comment by davla** [comment]
Oh, I was totally wrong. Good start :joy::joy::joy:
I'll take a deeper look at how things work. In the mean time, if you have some tasks you think I can help with, just buzz me.

**Comment by deadc0de6** [comment]
@davla sure and let me know if you need some info. BTW I have started a [contribution](https://github.com/deadc0de6/dotdrop/blob/master/CONTRIBUTING.md) doc but it only has basic info.

**Comment by davla** [comment]
So, here I come. I have a stub implementation of the `import_profiles` funcionality. So stubby that I don't feel like opening a pull request yet :grin: Just tell me if I'm going in the right direction.

Here (davla/dotdrop@fefda0c) I got started with `import_profiles`. I assume something like this:
- `import_profiles` is a key in `config`, like `import_actions` and `import_variables`. It stores a list of config files path.
- The imported profiles are full config files. Profiles depends on pretty much anything else in the config
file, so there's little point in having a stripped down version which only contains profiles, at least in the early stage we are in now.

You can see the bulk of the implementation [here](https://github.com/davla/dotdrop/commit/fefda0c9b9239bda0319d50b1200eb85d74aaf01#diff-2cdd9ab589054ace54d2398ed80664a6R257): pretty much I recursively create a `Cfg` object for all of the paths and then merge in the relevant parts. I'm aware that I do no error handling and the `dict.update` method is not the right way of merging things, but this is just to get the general idea. I've also written [a test](https://github.com/davla/dotdrop/commit/fefda0c9b9239bda0319d50b1200eb85d74aaf01#diff-423890b7e3c2aa4791f9e203b7f194cbR203) to check whether the dotfiles are included from another config file.

Here (davla/dotdrop@1ef0eed) I started with tracking the config object in the `Dotfile` class. Tell me if this is what you meant.

Finally, I was thinking whether a `Profile` class would make sense. It's a big refactoring, but right now you're pretty much just using the profile name as a key in some dictionaries and profile information is scattered all around. I couldn't really figure out where to place the config object a profile is defined in, and indeed I didn't add it.

**Comment by weilbith** [comment]
> The imported profiles are full config files

Is this working recursive? So can I define `import_actions` in an imported file again? This could become pretty huge in options how to split your configurations like:
```
|- dotfiles
L config
   |- env
   |- config.yaml
   |- actions.d
   |   |- common.yaml
   |   |- installation_utils.yaml
   |   L ...
   |- variables.d
   |   |- environment.yaml
   |   |- arch.yaml
   |   L...
   L profiles.d
       |- work
       |   |- programming.yaml
       |   L...
       L private
           |- mail.yaml
           L...
```

**Comment by weilbith** [comment]
Okay I'm really not sure if this is just super useless or brilliant. Somehow it looks nice for me. xD
But breaking it down in some "features":
- importing of "whole files"/"profiles" works recursive
- import statements can parse POSIX regex (eg. `folder/*.yaml` or `folder/**/*.yaml)
- intelligent parsing for missing definitions:
  - when the `profile` section is missing, a default one with the name of the file and all defined dotfiles is created
  - importing "whole files"/"profiles"  is hierarchy aware, so that having `profiles.d/**/*.yaml` imported means that each subdirectory becomes a profile with the name of the folder and `import_profiles` for all files in this subfolder

**Comment by weilbith** [comment]
Evaluation of the configuration must be done at the end. Else some checks will fail because a dotfile is probably not known at this point because the recursive import hasn't seen it at this point.

**Comment by davla** [comment]
- The way i sketched it now should be recursive.
- The globbing should give very little problems. POSIX regex would likely introduce a dependency, so I can't promise much.
- The rest seems too much like _convention over configuration_ to me, and I'm definitely not a big fan of it. especially when your configuration is a nice thing like a YAML file. But I'm not the head of this project, we'll see what @deadc0de6 thinks about this.

**Comment by deadc0de6** [comment]
@davla Wow that's some very nice job, thanks a lot!

Here are a few notes:
* if we go into the *import entire config file* idea we should rethink multiple things, that is:
  * name it `import_configs` instead of `import_profiles`
  * refactor the way the config is currently done with a top config handler (`Config` class for example) which aggregates imported config files (`Cfg` class for example)
* I agree with @davla, I'd rather go for explicit than implicit (configuration over convention)
* POSIX regex can already be simply integrated for the paths as it is already used for *ignore* pattern with [fnmatch](https://docs.python.org/3.4/library/fnmatch.html)
* yeah having more classes in the configs would definitely make sense (like for example *Profile*) to better structure the way things are

This is still a lot of work but from my point of view this is two different features: the ability to import profiles from an external file and importing an entire config. They fill both different purposes.

I understand the idea of being able to import entire profiles (clean config, split by *type* of profiles, etc) but I have more difficulty understanding what purpose serves importing entire config files. One must know that when importing entire config file, the multiple elements will not be *shared* across configs and it would then be more difficult to avoid redundancy for example. Still I'm not saying it shouldn't be done, I just don't see real use-cases.

**Comment by davla** [comment]
> Explicit is better than implicit.

I love you :heart_eyes: 

Anyway, my decision of importing entire config files was purely pragmatic there:
- I didn't want to refactor the parsing to deal _only_ with profiles. Not yet, at least.
- If you think about it, importing a profile effectively imports most of the config file. Indeed, you need:
  * variables
  * dynvariables
  * Dotfiles, which in turn imply
    + actions
    + transofrmations
    + default linking
    + dotpath (this can be avoided by using absolute paths in the Dotfile class, probably)

Then, there's so little left in the config file that you don't need when importing a profile that it makes very little sense to me to have a dedicated `import_config`. It would include things such as `longkey` that are not really worth importing, aren't they?

**Comment by deadc0de6** [comment]
Makes sense, I see your approach. However for clarity (since it will import *entire* configs and not profiles), let's name that `import_configs` if you don't mind. I can almost already see a new feature requests for importing entire profiles (and not the rest) and we will have a name collision.

**Comment by davla** [comment]
Yeah, sure, it's just a name.

As for this hypothetical feature request to import entire profiles, do you mean just importing the profiles from a config file, and ignoring whatever does not concern profiles, such as `longkey` or `workdir`? This is pretty much what I'm doing. Then the difference with importing whole config files only lies in somehow handling  `longkey` or `workdir` and the rest. I think we should make this clear now that the iron is hot.

**Comment by deadc0de6** [comment]
Exactly, my understanding is that files imported through `import_profiles` would only contain the `profiles` entry and its sub-entries (like for `import_variables` and `import_actions`) while `import_configs` would be an entire config files (`dotfiles` entry, `profiles` entry, `variables` entry, etc)

**Comment by davla** [comment]
Ok. I'm focusing on `import_configs`, as it is quicker to implement now, so we can have the feature earlier. I also feel like importing single profiles would be easier after the refactoring of the model you were talking about, so let's take our time for that.

**Comment by deadc0de6** [comment]
Absolutely, thanks again for your help!

**Comment by deadc0de6** [comment]
@weilbith can you give a try at the [parsing-refactoring](https://github.com/deadc0de6/dotdrop/tree/parsing-refactoring) branch? It does support `import_configs` (with recursion) as well as globs for any `import_*` entry.

**Comment by deadc0de6** [comment]
The branch [parsing-refactoring](https://github.com/deadc0de6/dotdrop/tree/parsing-refactoring) will be merge in master soon and I will release a new version on pypi soon after.
