### ISSUE TITLE
[docs] import_config docs

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#126]
Here it is the documentation for `import_configs` https://github.com/davla/dotdrop/wiki/config.

I added `import_configs` in the keys in the first section, trying to keep it as small as possible, but still giving the idea of what it does. Then [the import config files](https://github.com/davla/dotdrop/wiki/config#import-config-files) section shows an example, which I hope to be understandable.

Repo link for merging: https://github.com/davla/dotdrop.wiki.git

**Comment by deadc0de6** [comment]
Merged, thanks again!!

**Comment by davla** [comment]
Have you checked it, at least? Is the feature as you expected?

**Comment by deadc0de6** [comment]
I did check it yes, thanks for the work. You and @weilbith were the initiators and will probably be the first users of this feature so let's see how this works out for you and adapt it on the way. I will start thinking how to refactor the class hierarchy to manage different/external configs.

**Comment by davla** [comment]
[Well...](https://github.com/davla/dotdrop/tree/model-refactoring)

**Comment by weilbith** [comment]
Great work @davla!
Love the possibilities of this tool!

**Comment by weilbith** [comment]
Did we had an issue for the import globs? 🤔

**Comment by weilbith** [comment]
@deadc0de6 again new PyPi release? :thinking:

**Comment by deadc0de6** [comment]
@weilbith we are currently refactoring (thanks @davla) how the config management is done internally and I'd rather wait for it to be done before releasing a new version, especially since the current `import_configs` feature is still experimental.
You can still use the master version by installing it locally with `python3 setup.py install --user` for example in the mean time.

**Comment by weilbith** [comment]
Okay, that are good arguments :+1:
