### ISSUE TITLE
[Refactoring] External config

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#128]
I linked it in #126, but there's still pretty much no explanation in the code, so I need to comment it now.

So, it all started because profiles are kept as a reference to the yaml file content in the `Cfg` class. This means that they cannot really be changed unless the yaml file should also be changed, like in `dotdrop import`. This creates problems when merging in profiles from a different file.

To address this problem, I though of a parse-serialize approach: we parse everything to Python objects, ditching any reference to yaml files afterwards, and then we serialize it back to yaml files. I implemented this in the `model` submodule, which contains classes that are only responsible  for parsing-serializing and storing information. All the "operations" should be somewhere else.

This creates problems when more than one file is around: even without external config files, if actions and variables defined in an external yaml file are merged with the actions and variables defined _within_ the config file, they will be serialized in the config file.

To address this, I can come up with two approaches:
- __Keeping track of where objects come from__: This is the one currently implemented, where 
  every class has a `source` attribute. For example, actions defined in external files will have 
  this attribute set to the file name, while those defined within the config file will have it set to the 
  corresponding `Cfg` object. This means that the `Cfg` object can filter only actions whose 
  `source` attribute is `self` before serializing.
- __Having a *global store* where everything is kept__: This one I came up with now. The idea 
  is _not_ to merge externally defined resources with the local one, but rather gather everything 
  in the _global store_. For instance, actions defined in other yaml files will _not_ be merged 
  with the local actions, defined _within_ the config file, but will be rather saved in an 
  `ext_actions` attribute. Then, a gatherer crawls the model instances to get _all_ the actions, 
  _all_ the profiles and so on, and that's where operations are done on.

Pros and cons of the two approaches:
- __Keeping track of where objects come from__:
  + __Pros__:
    * Lightweight refactoring of the "command" layer: the top-level `Cfg` class contains all the
      data, like it is right now.
    * Less error-prone
  + __Cons__:
    * Heavyweight refactoring of the "model" layer.
    * A _lot_ of work.
- __Having a *global store* where everything is kept__:
  + __Pros__:
    * Lightweight refactoring of the "model" layer: accessor methods like `get_variables` for 
      anything else should probably do the trick. 
    * Less work than the other.
  + __Cons__:
    * Heavyweight refactoring of the "command" layer: it has to interface with a different 
      data structure (the _global store_).
    * Hacky and error-prone.

I'd personally go for the first approach, I think the two of us are enough to complete the task in human times.

**Comment by deadc0de6** [comment]
Yeah like you say we need to somehow *detach* the lower-layer yaml file and its representation in dotdrop. Those two elements are currently tightly linked and this is problematic for being able to properly and cleanly handle multiple configs.

I personally like the approach of having two layers, one for representing a config file's yaml content (loading yaml, parsing fields, validation, etc) and one upper layer for the representation of those elements in dotdrop (as objects, lists, dicts, etc). Those two layers should be decoupled.

The big issue is not to load config files but it is to be able to write-back to them (and especially to the correct one). But, as a user perspective, the only elements that need to be write-back, due to the `import` command, are a profile entry (if it doesn't exist already), a dotfile entry in a profile and a dotfile element. So I would suggest taking your first approach but to simplify it radically by doing one of the following:

* keeping a `from/source` attribute only for the above elements to know where they should be write back
* declare that importing a new dotfile always creates/adds it in the *main* config. We thus wouldn't have to handle any `from/source` attributes.

I'm strongly in favor of the second option because it is much simpler/clean and still allows a user to import to a specific config file by using that config file on its own. I'm however interested to know your opinion since you might have other use-cases that would negate this approach maybe.

**Comment by deadc0de6** [comment]
rough schematic:

**CfgAggregator**: represents the higher layer of the config as used by any other elements of dotdrop
- pointer to main config file
- list of sub config file
- methods to get different (aggregated) elements (get_variables, etc)
- hidden methods for aggregating all sub-configs elements in one top/aggregated element (for example all variables from all sub-configs in one variables element)
- higher level objects (list of actions object, etc)
- a method for importing a new dotfile that will take care of calling the right sub-config and save it

**CfgYaml**: class for parsing and handling the config yaml file
- load from yaml
- parse the fields
- patch any fields if need be
- save to yaml

The big parsing logic would be in `CfgYaml` while `CfgAggregator` would *only* aggregate each sub-config elements in one *global* element and provide methods for getting those.

**Comment by davla** [comment]
> I'm strongly in favor of the second option because it is much simpler/clean and still allows a user to import to a specific config file by using that config file on its own. I'm however interested to know your opinion since you might have other use-cases that would negate this approach maybe.

I'm also much in favor of the second approach. The command-line options to allow importing a dotfile somewhere else would be cumbersome, both from user and implementor perspective. Much easier to only work with the main config file.

I was not sure about the `from/source` attribute myself, but then I recalled that you wanted to have something like a _profile file_, where you list profiles, dotfiles, variables and so on. Pretty much anything you have in _config file_ but without the `config` key. In this case, `import` should write to the _profile file_ rather than the main config. But this is not the place to discuss this, neither the time. Just be aware that we would probably need it at some point.

Anyway, let me check that I understand your schematics correctly:
- `CfgAggregator`:
  + Pointer to _main_ `CfgYaml` object.
  + List of other `CfgYaml`.
  + Operates only with high level objects (`Dotfile`, `Profile`, `Action`...)
  + Methods to get those objects:
    * _non-aggregate_: from single `CfgYaml` (defaults to _main_)
    * _aggregate_: from all `CfgYaml`
  + Importing a dotfile adds it to _main_ `CfgYaml`
- `CfgYaml`:
  + contains a dictionary of the YAML file content.
  + parsing yields high-level objects
  + patching accepts high-level objects as well.

As a little implementation note, I'd try to avoid that `CfgYaml` becomes a huge class. In particular, I don't like that it knows all the parsing detail: a `Dotfile` should know how to parse itself, not `CfgYaml`. But this is just a matter of taste.

**Comment by deadc0de6** [comment]
Cool let's go for the second method then: insertion is only done in the *main* config and no pointers are kept from where each element comes from (no `from/source` attribute).

Yes your schematics look good. The insertion of a new entry (dotfile, profile or profile's dotfile) will be done through a single call to a method provided by the *main* `CfgYaml`. The `CfgAggregator` is the interface for the rest of dotdrop and no classes will directly *talk* with any `CfgYaml`.

```
dotdrop.py:import -> CfgAggregator:new(...) -> CfgYaml:new(...)
```

The *profile file* was a feature request (not from me directly) but if it needs to get included in the future, we'll handle that as any other `includes`/`imports` (actions, etc) ... I guess ... but that's another story. Based on this new layout this would be handled by the `CfgYaml` and would appear on the upper layer (in the `CfgAggregator`) as any other profile entry.

I tried to keep the *yaml stuff* in the config file only to avoid to have to spread it all over. It's not perfect and your approach is valid too. I didn't have that many objects back then and thus didn't make sense to spread the parsing to each *part*. However now that we have multiple objects (or to-be-created), it would be a good approach I agree. In the end they all would have to parse a dictionary/list so that's fine. We should just be careful with inter-dependencies.

BTW if you don't mind, I'd rather keep the sources flat with no subdir, especially if that feature only adds a few classes (`Cfg` -> `CfgYaml` and the new `CfgAggregator`, `Profile`, etc).

So if I summarize we would have the following objects:
* **new** `CfgAggregator`: represents the config aggregator with lists of objects
* **new** `CfgYaml`: yaml parser
* **new** `Profile`: represents a profile with its list of dotfile and other options
* **new** `Config`: represents configs (the `config` entry) from a config file
* `Action`/`Transformation`: represent actions and transformations
* `Dotfile`: represents a dotfile entry

How do you see the next steps, what have you done yet or are interested to work on?

**Comment by davla** [comment]
> BTW if you don't mind, I'd rather keep the sources flat with no subdir, especially if that feature only adds a few classes (Cfg -> CfgYaml and the new CfgAggregator, Profile, etc).

I guess you don't like nested classes too, then :smile: I'll make them all top-level, then.

So, the new `Config` class is already there, it's `Config.Settings` in my branch. I just need to add the couple of new keys you introduced recently, nothing hard.

As for the rest I'd rather go for the `CfgYaml` part: I've not really looked much into dotdrop commands, and I actually sketched the `Profile` class, but didn't push it. I also have a few demands on how to do it, as you have seen, so it's just the natural choice.

As for the next steps, I suggest I go a bit further, and then I open a pull request and explain my interface, so that you can start doing the rest, adapting the interface to your needs. At that point we'll have to do some tighter integration and we'll see if pull requests will still be a feasible way to go about it.

**Comment by deadc0de6** [comment]
Sounds good to me, ping me if you need help. Thanks!

**Comment by deadc0de6** [comment]
@davla ok for you to add a link to [your dotfiles](https://github.com/davla/dotfiles) in the [people using dotdrop page in the wiki](https://github.com/deadc0de6/dotdrop/wiki/people-using-dotdrop)?

**Comment by davla** [comment]
Well, I'm not done setting up yet, I don't know how much you want to show that off :smile:
