### ISSUE TITLE
[feature] Profile groups

### ISSUE THREAD

**Issue by fennerm** [deadc0de6/dotdrop#155]
I switch between a lot of different servers and local machines and it gets kind of annoying to write templates like:
```
{%@@ if profile == 'server1' or profile == 'server2' or profile == 'server3' @@%}
foo=x
{%@@ elif profile == 'linux_pc1" or profile == "linux_pc2" @@%}
bar=y
{%@@ elif profile == 'mac_pc" @@%}
car=True
{%@@ endif @@%}
```

It would be nice if I could write:
```
{%@@ if profile in server @@%}
foo=x
{%@@ elif profile in linux_pc @@%}
bar=y
{%@@ elif profile in mac @@%}
car=True
{%@@ endif @@%}
```

I have this implemented in my personal dotdrop fork. Is this something you'd be interested in merging if I clean it up and submit a PR?

**Comment by deadc0de6** [comment]
Sure, that sounds pretty neat! :+1:

I'm guessing your fork is based off of the master branch? We have however recently refactored the whole config parsing in the [parsing-refactoring branch](https://github.com/deadc0de6/dotdrop/tree/parsing-refactoring) (which will be soon replacing the current parsing solution) and thus it'd be awesome if you could direct your PR against that branch instead of master.

A lot of things changed between master and [parsing-refactoring](https://github.com/deadc0de6/dotdrop/tree/parsing-refactoring) and I do understand that this might mean quite some more work on your end to *port* it to the new code. I'm however available for help if you need. I'm of course also ready to port it myself in case you don't have time for it. In which case just do a PR against master with what you have now and I'll port it from there. 

Just let me know what suits you better.
Thanks for your help!

**Comment by deadc0de6** [comment]
The `parsing-refactoring` branch has been merged into master. If you feel like it, you can PR against master with your feature, thanks!

**Comment by fennerm** [comment]
Cool I haven’t had time to take a look at this yet to be honest but I’ll make a PR when I get a moment. Thanks!

**Comment by fennerm** [comment]
I actually don't think I'm gonna get time to implement this sorry. Feel free to close.

**Comment by deadc0de6** [comment]
No worries.

Similar behavior can be obtain by using variables, for example
```
dynvariables:
  os: uname -s | tr '[:upper:]' '[:lower:]'
```

or define specific variables in different profiles and play with those in the templates.
