### ISSUE TITLE
[feature] Deploy config on remote host vis ssh

### ISSUE THREAD

**Issue by fwarmuth** [deadc0de6/dotdrop#191]
Hey,
I am annoyed from adding not trustworthy machines to my dotdrop repo to just enroll my configs. Using a lot of different machines mostly via ssh, sometimes these machines are not connected to the internet at all, making it even worse. Copying my whole repo via scp to then call dotdrop to install my "ssh profile" is possible but could be easier. 

**I would like:**
A feature so that i can call `$ dotdrop install -p 'ssh' -r ladmin@172.16.1.1`
**Expected Result:**
config profile "ssh" should be deployed on the remote machine (172.16.1.1) using 'ladmin' as user.

regards!
btw. i love dotdrop!!!!!!!!!   
maybe i will do it on a branch and open a PR, but that could take some time.

**Comment by deadc0de6** [comment]
Hey,

Thanks for submitting this. Yeah I understand your use-case.
Cool thanks, always happy when dotdrop is being useful :+1:

Let's first consider our options here before directly implementing this entirely in dotdrop.

**Option 0: manually transfer everything** - bundle dotdrop into a self-contained virtualenv, copy it over with `scp` or similar and execute it there.

**Option 1: implement the ssh wrapper** - gather all filesystem operations (`os.path`, `subprocess`, etc) in some class hierarchy to be able to implement an ssh filesystem operation class. That would mean however that everything will be somehow executed from the local host on the remote host through ssh and thus a lot of data will have to be sent over (config file variable resolutions, `actions`, `transformations`, copy file over for comparison, etc). At the end doing a simple `scp` and executing dotdrop on the other side might be easier.

**Option 2: copy locally deployed remote home dir** - We could also deploy locally a *fake* home directory and install the profile's dotfiles there and then copy the *fake* home to the remote host with `rsync` for example. Remains the problem of variable resolution and system dependent elements.

I like option 0 since it could be easily wrapped into some bash script to execute the entire thing automatically. I'm not really in favor of option 1 as it involves quite some work and could quickly become complicated to maintain. Option 2 is nice too but the issues with the ability to remotely resolve stuff needs to be fixed.

Do you see other options?
I'd be ready to implement an helper script for option 0 if that could help you?

**Comment by hargoniX** [comment]
I was actually thinking about implementing Option 1 just yesterday, I'll fork dotdrop and look into it. In my edge case I can actually not use Option 0 as the server I want to deploy my dotfiles to does only allow people to upload stuff to it but not the other way round so I coulnd't git pull inside my local (on the server) dotdrop environment. And for option 2,  you already explained a few issues. If the code turns out too complex to maintain as you fear I guess I'll just stick to scping every directory / file I want over.
