### ISSUE TITLE
[help] Can I force dotdrop to compile and write templates on every install?

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#259]
Can I force dotdrop to compile and write templates on every install RUN?
I use jinja macros and includes - it works well for the first install but not on every consecutive install

regards

**Comment by deadc0de6** [comment]
I'm not sure to understand, can you provide me with a concrete example of what you're trying to do?

**Comment by niksfirefly** [comment]
Well i create some big config files with mulitple concatenated parts using jinja
for example I got .bashrc
```
# {{@@ header() @@}}  - {{@@ d_date @@}}

{%@@ import 'macros' as macros with context @@%}
{{@@ macros.concats() @@}}
{{@@ macros.include_vars() @@}}
```
where d_date is dyn variable compile date
macros concatenates part files and includes another ones based on vars profiles

I thought that It would compile every time due to changing d_date
but it works only for the first install - ignoring consecutive install commands

It is old concept working for me but dotdrop changes so in meantime I might missed some warnings about templating

regards

**Comment by deadc0de6** [comment]
Yes it should install each time. With the `d_date` part, the template should always install since it would differ from the installed file. 

* Do you get any interesting info when running with `--verbose`?
* Have you tried to do it with only the date part in the dotfile?
* is the resulting date part in the installed dotfile correct?

I'd like to help but I would need more info to be able to reproduce:

* dotdrop version and how it is installed
* config file (or at least the part with the `d_date` and the concerned dotfile)
* the dotfile (or at least a minimal version)
* debug logs of the installation of that specific dotfile (run with `--verbose`)

**Comment by deadc0de6** [comment]
Here's what I tried

```bash
$ cat dotfiles/test          
# {{@@ header() @@}}  - {{@@ d_date @@}}
```

`config.yaml`
```yaml
dotfiles:
  f_test:
    src: test
    dst: ~/.test
profiles:
  hostname:
    dotfiles:
    - f_test
dynvariables:
  d_date: date
```

```bash
$ ./dotdrop.sh install -f    
	-> copied /home/user/dotdrop/dotfiles/test to /home/user/.test

1 dotfile(s) installed.

$ ./dotdrop.sh compare   
=> compare f_test: diffing with "/home/user/.test"
-# This dotfile is managed using dotdrop  - Mon Sep 28 07:44:34 PM
+# This dotfile is managed using dotdrop  - Mon Sep 28 07:44:37 PM
```

@niksfirefly is the above working for you?
