### ISSUE TITLE
Actions on files imported via a directory?

### ISSUE THREAD

**Issue by kevinconley19** [deadc0de6/dotdrop#262]
Any ideas how to handle permissions when backing up to as USB drive with exFAT?

My original thought was to use a default action to change the permission. However, i just realized that when a directory is imported the containing files get imported however action don't get applied to them upon an install. 

Any ideas on how to handle actions on files INSTALLED (fixed from import) via a directory dotfile?

**Comment by deadc0de6** [comment]
Using a dotfile action on the dotfile directory is a good idea if you need to *fix* the permissions on dotfile installation. 

Actions don't apply to import, only to installation. Dotdrop will *mirror* the permission of the file when importing (what makes sense since you expect that running install after importing wouldn't actually change the file or its permissions).

I'm not sure to understand why you would apply actions when importing file since this is a one-time operation. Can you elaborate?

**Comment by kevinconley19** [comment]
Sorry - install.

I keep my dotdrop dir on a usb using exfat. Thefore, when i INSTALL the permissions are 777.

**Comment by deadc0de6** [comment]
I see ... well this is definitely not optimal. I would suggest to use a filesystem that properly handles unix permissions, this is the best workaround.

Otherwise I see hacky ways to do it.

Either you want to have the same permission to all your dotfiles (which might not be very clean or even wanted depending on what dotfiles we are talking about) and thus implement an action that applies to all of them or you keep the permissions in a different file and execute an action (script) after the installation of all dotfiles.

This is hacky and ugly but it could work:
```bash
$ stat -c "%a %n" ~/.tmux.conf ~/.gitconfig > /tmp/permissions
$ cat /tmp/permissions 
644 /home/user/.tmux.conf
644 /home/user/.gitconfig
```

you then create a default post actions that would run the following after all dotfiles are installed and reset their permissions
```bash
$ while read line; do chmod $line; done < /tmp/permissions
```

**Comment by deadc0de6** [comment]
Indeed you can either use a profile action or even a *fake* dotfile to make sure this is always executed (see the [fake dotfile doc](https://dotdrop.readthedocs.io/en/latest/config-details/#fake-dotfile-and-actions)).

**Comment by deadc0de6** [comment]
Closing this. Feel free to re-open if you any questions.
