### ISSUE TITLE
[help] Is there any way to disable the templating engine altogether?

### ISSUE THREAD

**Issue by nestor-custodio** [deadc0de6/dotdrop#267]
### The Setup

- I have a dotfile dir (call it `.a`), which I want to symlink as `~/.a`.
- This directory contains some 19000+ files in a deeply nested structure.
- Somewhere in this tree are one or more files *whose contents I do not directly control* and that happen to contain one of the magic character sequences (`'{%@@'`, etc) that trigger templating behaviours.

### The Problem

Rather than performing a **0 time** symlink making `.a` available as `~/.a`, dotdrop instead:
- Reads all 500+ MB of data in `.a` looking for the magic templating character sequences.
- Copies all 500+ MB worth of files from the source to a working location.
- Moves the copied files into their final `~/.a` location.

This not only *unnecessarily duplicates every file in `.a`*, but it also *takes several minutes*, and (most importantly) **mutates my files while trying to do variable replacement**.

### My Question

Not only do I not want to run the template check in `.a`, but I have no need for this feature *at all*.

Is there a flag or config file setting that disables the templating engine entirely or at least disables it by default so it can be turned on selectively for specific dotfile entries? (I have pored over the documentation but have not yet been able to find any such mechanism myself.)

If the answer to this question is a NO, then I would like to escalate this *help* issue to a **bug** report, as dotdrop's current behaviour is to unnecessarily (a) read, (b) duplicate, and (c) mutate files based on factors outside of the user's control.

Thanks in advance for any help you can provide!

---

I do realize that the number and size of these files (in addition to the fact that I don't myself control their content) probably places me well in the minority when it comes to intended use cases, but these files *are* part of a dataset that I *do* want to make available to myself across multiple systems, and I *do* feel like dotdrop is built specifically for this usage as it was fulfilling its role admirably until I happened to run into a file with one of the magic character sequences.

**Comment by deadc0de6** [comment]
Ok, I will start by saying that dotdrop is a dotfiles manager and obviously was not meant to be a tool to manage/handle `19000+ files` representing a total of `500+ MB` of files that the user `do not entirely control` ;-) 

When I started dotdrop I tried to chose delimiters that were very unlikely to come up in *normal* config files (that's one of the reason I even didn't keep the jinja's default ones) but well, it happened. Are these sources files? 

My first naive solution to this is to use transformations to handle your directory. This would allow first to reduce the total size to sync back and forth but also to solve your issue with dotdrop parsing your file (since dotdrop won't bother sneaking in your compressed file, it is not that nasty ;-)). You can find a little example in the doc ([here](https://dotdrop.readthedocs.io/en/latest/howto/store-compressed-directories/)) and I'd be happy to help if you have any issue setting it up. **But** (and I guess this is a big but for you) transformations do not work with dotfiles that are to be linked.

So if you want to keep symlinking that dotfile we'd have to find another solution.

I see two ways to solve this:

* provide a way for the user to change those delimiters (through some config entries)
* provide a way for the user to disable explicitly templating on specific dotfiles

Tbh I think option (2) (allowing users to explicitly disable templating) is not such a bad idea and could well be used by others.

I see something like that:
```yaml
config:
  template_dotfile_default: yes
dotfiles:
  d_somedir:
    dst: ~/.somedir
    src: somedir
    template: no
```

That way you could either disable templating for all your dotfiles (with the use of `template_dotfile_default: no`) or keep the default of templating all dotfiles but disable it for a specific file (with the dotfiles entry `template: no`).

And this could also avoid to have all *linked* dotfiles (even the ones not using any templates directives) to be symlinked first to `~/.config/dotdrop` before being installed (what you call the *unnecessarily duplicates* in your help request).

Would that be a solution for you?

**Comment by nestor-custodio** [comment]
Agreed option 2 seems like the more robust approach, and yes that would absolutely resolve my issue.

I'd love to submit a PR for this myself, but I'm afraid my Python-ese is nowhere near as fluent as I'd probably need to make this happen reasonably quickly.

Very much appreciate your prompt response to the issue, BTW.  👍

**Comment by deadc0de6** [comment]
Ok, I'll work on that and keep you posted when I have something concrete

**Comment by deadc0de6** [comment]
The following new config entries are now available: `template_dotfile_default` and `template`:

You can disable templating for a dotfile with the entry `template`
```yaml
dotfiles:
  f_test:
    dst: ~/.test
    src: test
    template: false
```

Or you can disable templating globally for all dotfiles (default value of `template_dotfile_default` if not set is `true`). This is applied to all dotfile that don't specifically define `template`.
```yaml
config:
   template_dotfile_default: false
```

see also the related doc:
* [config format doc](https://dotdrop.readthedocs.io/en/latest/config-format/)
* [templating doc](https://dotdrop.readthedocs.io/en/latest/templating/#templating-or-not-templating)

**Comment by nestor-custodio** [comment]
Can confirm this works like a charm. The install operation runs *so much faster* than even before, and without issues! Looking forward to the updated Snap package release.

Thanks so much!!

**Comment by nestor-custodio** [comment]
Quick follow-up: is there a date set for the upcoming v1.2.2 release, @deadc0de6 ? Definitely not trying to rush you -- just trying to plan some of my work and personal projects for the coming weeks, as new VM deploys are currently blocked until the above fix makes it onto a Snap release.

Thanks in advance for any info you can provide.

**Comment by deadc0de6** [comment]
New version 1.3.0 released [on snapcraft](https://snapcraft.io/dotdrop)

**Comment by nestor-custodio** [comment]
![giphy](https://user-images.githubusercontent.com/8892759/96353568-e4831e80-1092-11eb-975f-77725b3326bc.gif)
