### ISSUE TITLE
[help] Trying to understand DotDrop better

### ISSUE THREAD

**Issue by josaladino2** [deadc0de6/dotdrop#270]
**What I am trying to achieve**
I'm not sure still how dotdrop relates to git and where one leaves off and git takes over.
I get dotdrop import/install ok.  
Import seems to bring the file into the dotfiles repository and config.yaml
install seems to turn the local dotfile from a file/directory into a link pointing to the dotfiles repository.
If these processes do more than that, I have not seen it yet so please fill me in.
When I do dotdrop update, I expected that it would git add the outstanding files in the dotfiles repository but no it didn't.
What exactly does dotdrop update do?  
After I have done dotdrop install, git status does not show any files in staging
I did git add dotfiles to add the dotfiles local repository to the remote repository.  was that correct?
They show up in the remote repository ok.
With this setup, what does dotdrop update do?

Also, one of the files I import/installed was a directory .joey2/
It imported ok and installed ok as well.
it was an empty directory so it did not upload to the remote.  I think I understand that.
I put a file in that directory
Now I'm at a loss as to how dotdrop manages the file inside that directory.  Can I drop a file into the .joey2 directory and then dotdrop update will automatically upload it to the remote repository?

I'm wondering if this is where link_children comes into play.
So sorry for the trouble but can you help me with these missing peaces in my dotdrop/git knowledge?

Thanks.
BTW, I have looked at many dotfile management systems and I this one the best.  I really want to make use of it because of its features.  Thanks for your help.
**What I have tried so far**

**Comment by deadc0de6** [comment]
Dotdrop is a dotfiles manager while git is a version control system. Per se dotdrop
does not depend on git except if you install it as a submodule.

It's up to you how you want to version, sync and store your dotfiles managed by dotdrop. 
Git is mentioned a lot since it is the usual ways of versioning files (and dotfiles) but
you can use any other means if you want to (cp/scp, svn, cloud, etc).

Regarding all dotdrop commands, I would suggest you take a look at the
[doc](https://dotdrop.readthedocs.io/en/latest/usage).

The `update` command is not related to git, it updates the dotfile
managed by dotdrop from the filesystem (see the [doc](https://dotdrop.readthedocs.io/en/latest/usage/#update-dotfiles)).
It is used when you change your dotfile directly in your home for example and
want the new version to be reflected in dotdrop.

Dotdrop `install` installs the dotfile to your file system so git won't
see any change since the dotfile is not changed in your repository
but on the destination where it needs to be installed.

In a way `install` is the opposite of `update` and vice-versa.
For example:

* `install`: *copies* the vimrc dotfile from your *dotpath* to `~/.vimrc`
* `update`: *copies* `~/.vimrc` to your *dotpath*

For `link_children`, I'd suggest you take a look at the example
[here](https://dotdrop.readthedocs.io/en/latest/howto/symlink-dotfiles/#link-children).

I hope this answers your questions.

**Comment by deadc0de6** [comment]
I have updated [the usage doc](https://dotdrop.readthedocs.io/en/latest/usage/) hoping it will be more clear. Since you seem to have struggled to understand how dotdrop works as a newcomer, what would you have expected to help you more, what documentation was missing? Thanks for your inputs.

**Comment by josaladino2** [comment]
Thx

--
____________________________
Joe Saladino [joe@bram.net] 
(From my iPhone)
+1(208) 971-7570

“You never realize Jesus is all you need
until Jesus is all you have.”
--Timothy Keller (The Prodigal Prophet)
