### ISSUE TITLE
[help]

### ISSUE THREAD

**Issue by josaladino2** [deadc0de6/dotdrop#273]
**What I am trying to achieve**
I am rather new to git.  I have exercised dotdrop quite a bit and yesterday I reported the bug with an empty directory not being deleted when the last file is deleted from the dotdrop repository.  I really want to use dotdrop.

That being said, I don't know the best way to set up the remote repositories.
Here is my setup:
I have my home directory set up as josaladino2/userfiles on GitHub.com
dotdrop is installed within ~/dotfiles

This is a 3 part question.
starting with dotdrop, if I enter ~/dotfiles and use git s I see a couple of files that are staged.  However, I don't have a remote setup for dotdrop.  Should I set up a remote like josaladino2/dotdrop for everything in the ~/dotfiles directory?
How do I upgrade/update dotdrop from time to time?

Or should I include dotdrop as a submodule within my josaladino2/userfiles like my fonts directory?

Or should I just include several key files and the dotfiles/dotfiles directory in my josaladin2/userfiles repository?

I think you would have a preferred way of setting up the remote repositories so they would be easy to manage/update, etc.

Thanks for your help.  Now I need to update my dotdrop after you make the fix. :-)  I suppose that I could just clone to pick up the fixes.  What do you suggest?  Thanks for your time.
Joe

**What I have tried so far**

**Comment by deadc0de6** [comment]
This is a personal opinion and others may have different views on this but versioning your entire home directory is imho not an optimal solution for multiple reasons:
* how do you manage sensitive files
* how do you handle binaries (since binaries and git don't play very well)
* how do you handle all the temporary files / test files / etc that don't actually have to be versioned (and shouldn't)
* home directories change a lot, do you always commit everything and push
* tools add all type of files in your home and although you probably need them, you don't always want to version them
* etc

It is hard to maintain and doesn't scale very well.

Those are all reasons I would suggest you change your approach to using dotdrop to manage those files. This is exactly the idea of dotdrop, handle all the dotfiles that are important to you and discard the rest. That way you can mirror your setup/configs to other hosts easily without having to care about all the rest.

I would suggest not to version your entire home and install only dotdrop. You then import all files that are important to you (for example your entire `.mybfuncs` directory with your scripts, etc). Dotdrop can live anywhere but people usually clone their dotfiles repository managed with dotdrop in their home.

These would be the different steps:
* create a repository on github named for example `dotfiles`
* clone it in your home (for example `~/dotfiles`)
```bash
git clone <your-above-created-repository-path> ~/dotfiles
cd ~/dotfiles
```
* use dotdrop to import all dotfiles you care about (`dotdrop import ...`)
```bash
dotdrop import ~/.mybfuncs
## import some more ...
```
* commit and push all your changes
```bash
git add dotfiles/* config.yaml
git commit -m 'importing stuff'
```

Also you need to choose how you want to install dotdrop (see [this doc](https://dotdrop.readthedocs.io/en/latest/installation/#installation) on what solutions are available to you).

Now you have a dotfiles repository that you can clone on another host and use `dotdrop install` to install all your dotfiles.
Any change you want to make to your dotfiles are either done directly in the dotfile on your filesystem and use `dotdrop update` to update the version in dotdrop (and then commit and push the changes) or directly in dotdrop *dotpath* (again commit and push) and then run `dotdrop install` to deploy it.

If you need more details on some of these steps, feel free to let me know.

How to apply the fix (or more generally how to update dotdrop) depends on how you have installed dotdrop. There's a doc for this [here](https://dotdrop.readthedocs.io/en/latest/installation/#update-dotdrop) but if you use anything else or need help with this, feel free to drop me a line and I'll try to help.
