### ISSUE TITLE
[bug] Horror - templating not working at all

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#284]
Dotdrop version 1.3.6
Using dotdrop: as a submodule
Ubuntu 18.04

After upgrade without any changes all templating is gone! on my all accounts and machines
Is there any significant changes? what is going on?

regards

**Comment by niksfirefly** [comment]
Is there a way (docs maybe) about the dotdrop downgrade?
I found snap package - will it be uptodate with pip/submodule version in future?

regards

**Comment by deadc0de6** [comment]
This was a bug introduced when attempting to improve (and speed up) the templating. It should be fixed now, sorry for the issue.

I will add a documentation about downgrading (I guess you mean when using as a submodule).
The [snap package](https://snapcraft.io/dotdrop), like the [pip package](https://pypi.org/project/dotdrop/) and the [aur package](https://aur.archlinux.org/packages/dotdrop/) are all at the same version, latest stable which is 1.3.6 currently.

**Comment by deadc0de6** [comment]
[Here](https://dotdrop.readthedocs.io/en/latest/installation/#downgrade-dotdrop-submodule) is the doc on how to downgrade dotdrop (when used as a submodule) to its latest stable version.

**Comment by niksfirefly** [comment]
Thanks for clarification. I learn valuable lesson as some hosts ssh access is disabled due to this bug.

Will be 1.3.7 bugfix release today?
Is there any downsize when I migrate from submodule to pip or snap install style?
I believe simple change of alias dotrepo and removing sudirectory dotrepo from my-dotfiles is enough?
or I missed something?

regards

**Comment by deadc0de6** [comment]
Stable version 1.3.6 (currently on pypi, snap and aur) is **not** impacted by the above bug. Also the master branch is not impacted anymore since it was fixed. Next version (1.3.7) will be release soon but probably not today since I still need to test some stuff and fix some issues. For now the big different between 1.3.6 and the master branch is
* speed up of templating through the use of python-magic instead of `file`
* ask before dereferencing symlinks (#184)
* actively checking for python dependencies

If you want to change from submodule to pip/snap/aur, you just need to install the version you are interested in and then update your alias or anything you use (`dotdrop.sh`, etc) to use the installed version instead of the submodule. You can then remove the submodule.

BTW multiple versions of dotdrop can be used in parallel since you only need to make dotdrop point to your config file (`config.yaml`) and since everything is relative to the config file the submodule version and a pip/snap/aur version can be used in parallel.

**Comment by deadc0de6** [comment]
@niksfirefly new version 1.3.7 released!
