### ISSUE TITLE
[feature] cmd_remove ask for delete dotfile.dst

### ISSUE THREAD

**Issue by loynoir** [deadc0de6/dotdrop#306]
### Feature request:
[cmd_remove](https://github.com/deadc0de6/dotdrop/blob/0997b8b78db82ae8365cde347cb0af3c57c75e6f/dotdrop/dotdrop.py#L576) ask for delete `dotfile.dst`

### Background:
Before migrate, A.conf includes B.conf.
After migrate, A.conf not depends on B.conf any more.

### Actual behavior:
```sh
dotdrop remove ~/B.conf
```
1. remove dotfiles/B.conf
2. ~/B.conf is now orphan
3. no orphan hint or manual delete hint

### Expected behavior:
```sh
dotdrop remove ~/B.conf
```
1. remove dotfiles/B.conf
2. ask for remove ~/B.conf
3. or hint on manual remove

### PS: 
Really thanks for this great tool 😘
It's AWESOME GREAT!
Templating and the three types supported, soft link, copy, link children, really describe dotfiles types. 😃
After using homesick, homeshick, chezmoi, stow, I think I found my anwser😃
Thanks a lot, bro!

**Comment by deadc0de6** [comment]
Cool, happy it helps :smiley:

The command name might be misleading, should maybe have been `untrack` instead of `remove` but for back-compatibility I won't change it now. But anyway, dotdrop doesn't actually touch your dotfiles on the filesystem (unless you use link or something) and especially not when untracking them. 

What I could suggest is a little line per removed dotfile to make the user aware the file is now not managed anymore. Something like this:
```
dotfile "~/B.conf" not tracked anymore
```

Would that solve your issue?

**Comment by loynoir** [comment]
Yes. 😃
Thanks for this awesome tool.

**Comment by loynoir** [comment]
Just got dotdrop updated. Wow, you are awesome, bro. 😀
Jus got an idea.

### Feature Request
May be can add `loggingfile` option. 
Might not be very accurate name.
I mean something like 
```py
addHandler(loggingfile_handler)
addHandler(console_handler)
```

### Scenario
Although hasn't been, but someday I might miss to deal with untracked config file.

**Comment by loynoir** [comment]
I'm ok with or without logging. Dotdrop has already been a great tool for common cases. 😘
