### ISSUE TITLE
[feature] run once only bootstrap command

### ISSUE THREAD

**Issue by Syusyuly** [deadc0de6/dotdrop#310]
When using a brand new machine, you may need not only dotfiles, but also some common software that does not require additional configuration, and hooks may not be sufficient. We may need to introduce commands that are run only once to install these programs.

Currently there are config entries such as fake actions and default_actions, but neither of these can be guaranteed to run only once. Perhaps we need to introduce the `dotdrop bootstrap <boostrap_path>` command, as [yadm](https://yadm.io/docs/bootstrap) does.

**Comment by deadc0de6** [comment]
Of course you could use [fake actions](https://dotdrop.readthedocs.io/en/latest/config-details/#fake-dotfile-and-actions) and make sure your installation scripts are idempotent. Or work with some cookie file, for example
```bash
#!/bin/sh
cookie="~/.config/dotdrop.bootstrap"
if [ ! -e "${cookie}" ]; then
  # TODO - install stuff
fi
```

But this is just an idea.

From what I understand you're requesting to add a cli command, which when called will execute an arbitrary script passed as first parameter. I'm just wondering why you would not directly call that script instead of adding a level of indirection through dotdrop?

**Comment by Syusyuly** [comment]
Okay, you've made your point. Considering the fact that bootstrap is not a common action, it is acceptable not to introduce a new command.
