### ISSUE TITLE
[feature] TOML configuration file support

### ISSUE THREAD

**Issue by FunctionalHacker** [deadc0de6/dotdrop#343]
It would be awesome if we could use TOML instead of YAML to configure dotdrop. I could pretty easily whip up a script which converts TOML to YAML on the fly but I wanted to see first if there was interest to include support in dotdrop itself.

**Comment by deadc0de6** [comment]
That should work since I'm actually simply matching yaml to a `dict` so doing the same for `toml` should be possible (modulo such a lib exists). Let me take a look at this and get back to you.

Just for my own interest why toml instead of yaml, what would be the benefit of using the config in toml rather than yaml?

**Comment by FunctionalHacker** [comment]
> That should work since I'm actually simply matching yaml to a dict so doing the same for toml should be possible (modulo such a lib exists). Let me take a look at this and get back to you.

Awesome!

> Just for my own interest why toml instead of yaml, what would be the benefit of using the config in toml rather than yaml?

I just hate YAML for it's [oddities](https://www.bram.us/2022/01/11/yaml-the-norway-problem) and in general I don't enjoy programming languages/markup languages that require on whitespace. TOML is just a strictly typed INI file and I love the simplicity.

**Comment by deadc0de6** [comment]
I made a little script to play with `toml` and `yaml` and it seems first that two elements might not be properly parsed:
* `yaml` multi-line (what will be converted to a list of chars) `somekey: >-`
* `yaml` parses to `OrderedDict` while `toml` parses to `dict` directly

**Comment by deadc0de6** [comment]
@FunctionalHacker dotdrop is now able to load a `toml` config file. It is currently *quick-n-dirty* but might allow us to play with it before I go any further. It is available in the [toml branch](https://github.com/deadc0de6/dotdrop/tree/toml), can you give it a try with your config?

I made a basic convertor [yaml-to-toml.py](https://github.com/deadc0de6/dotdrop/blob/toml/scripts/yaml-to-toml.py). It probably doesn't cover all corner cases but ideally users should either start with yaml or toml and rarely convert. But I will handle conversion issues along the way.

I also provided a base config file [config.toml](https://github.com/deadc0de6/dotdrop/blob/toml/config.toml) where unfortunately the two mandatories entries `dotfiles` and `profiles` are not present since `toml` doesn't have the notion of empty/nil/nul/null. It will still work as this is *patched* by dotdrop on load.

Please let me know if it works for you. Once we are happy, I'll clean a bit and refactor (and document) and I will publish a new release with `toml` support.

**Comment by deadc0de6** [comment]
@FunctionalHacker `toml` support will be part of the next release.

**Comment by deadc0de6** [comment]
@FunctionalHacker this is now available in version v1.9.0

**Comment by FunctionalHacker** [comment]
Awesome! Thanks for your hard work!
