### ISSUE TITLE
How to update tracked dotfiles?

### ISSUE THREAD

**Issue by baudlord** [deadc0de6/dotdrop#4]
Thanks for the tool first of all! 

Now, my question is about how to sync updated files with dotdrop. Say I have a profile, 'laptop', and I locally change, say, '~/.vimrc'. There doesn't seem to be a way to update the dotfiles managed by dotdrop. How do I sync them? I can't call import again on them again, but there is no update command as far as I can tell.

**Comment by deadc0de6** [comment]
I would say there are two use cases:
* **The file is using jinja directives** personally I'm using the `compare` feature of dotdrop in order to identify the changes and manually porting them back on the dotfile(s) stored in dotdrop. This is quite some work at the beginning when you have to *template* all your files, but is just some maintenance work once everything is setup properly.
* **The file is not using jinja directives**: simply copy back the file into dotdrop's *dotpath* folder. 

Currently dotdrop won't allow to re-import a file that already exists in your dotfiles, returning an error like `... already exists, ignored !`. This to avoid erasing tracked dotfiles (especially if they are using jinja directives). We could think of an `update` feature which would copy back the file if it doesn't use any jinja directives. But if it does, the synchronization would be much more complicated.

Does that answer your question ?

**Comment by baudlord** [comment]
What you said about re-copying to the dotpaths is what I currently do, was just looking for a faster way to do that.

I think some sort of diff function would be useful, something like a git merge tool for dotdrop. I understand this may be hard to implement, though.

**Comment by deadc0de6** [comment]
Have you tried using the `compare` feature. It allows to see the different changes using `diff` in the backend. On the other hand, since dotdrop is on git, you can use all git commands/features once you have copied you file back (git diff, ...).

**Comment by roachsinai** [comment]
Hi @deadc0de6 , thanks for your work! As file using jinja directives like `zshrc` for me, I change setting directly to the  stored in dotdrop version. Then use `dotdrop install -t` to generate a temp .zhsrc, then copy it to `~` dir. So, is there a way to install a single file here?

**Comment by deadc0de6** [comment]
@roachsinai It wasn't possible until now but I implemented a way to select the dotfile keys when installing in latest commit. 

Let's say your `zshrc` is named `f_zshrc` in your config file, you would do
```bash
$ dotdrop install -t f_zshrc
```

By the way, dotdrop now provides a way to update the dotfiles directly as documented [here](https://github.com/deadc0de6/dotdrop#update-dotfiles). 
This issue is old ;-)
