### ISSUE TITLE
[bug] Post action -exec rm {} \; not work as expected

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#401]
Dotdrop version: v1.13.2
Using dotdrop: AUR archlinux

**Describe the bug**

Run post actions get error.

**Steps to Reproduce**

Add below action to config.yaml

```
actions:
  post:
    remove-backups: find {{@@ _dotfile_abs_dst @@}} -iname '*.dotdropbak' -exec rm {} \;
```

When run dotdrop install got below error:

```
[WARN] index error for action: "find /mnt/a/Scoop/persist/ccc -iname '*.dotdropbak' -exec rm {} \;" with "[]": Replacement index 0 out of range for positional args tuple
[ERR] post-action "remove-backups" failed
```

---

What's more, change action command to `remove-backups: find {{@@ _dotfile_abs_dst @@}} -iname '*.dotdropbak' -delete ;` works well.

**Comment by deadc0de6** [comment]
I'm guessing the `{}` from `find` is somehow confusing the parser (since actions support arguments with `{0}`, `{1}`, etc). Can you try with something like the following:

```
find {{@@ _dotfile_abs_dst @@}} -iname '*.dotdropbak' -print0 | xargs -0 rm 
```

Also the backup files can be disabled by setting [backup](https://dotdrop.readthedocs.io/en/latest/config/config-config/) to `false` in the config.

**Comment by roachsinai** [comment]
Thanks for your quick reply.

`find {{@@ _dotfile_abs_dst @@}} -iname '*.dotdropbak' -print0 | xargs -0 rm` did works.

I just wanna remove one or two dotfile's backup, like `mpv` will make warning when found these backup files under `scripts` folder.
