### ISSUE TITLE
[feature] ability to clean up real things

### ISSUE THREAD

**Issue by lictw** [deadc0de6/dotdrop#403]
Hello! 

First of all - thanks for the **great tool**! It's really the **most feature-rich** dotfiles manager for multi-ricing/overlaying: keeping bases/common things, patching them and extending in the rices etc., patching from other files, other repositories, any case can be implemented and I really like it!

But `dotdrop` misses some things for clean up dotfiles after another rice or experiment:
1. Way to delete all files belongs to `profile` or just a ability to delete files of some `dotfile` (without changing things in dotdrop, just clean up real things), may be with some filtering or advanced logic.
2. Ability to delete all not managed files/directories in `dotfile` if it's directory, now we only see warnings about this files and must delete them manually.

**Comment by deadc0de6** [comment]
Hello, thanks!
Happy you like dotdrop and it's useful to you :+1: 

Since we have all information in the config file, I think that's doable. It would be a new command (something like `uninstall`) and remove everything that was installed by dotdrop.

Regarding the ability to remove non-managed files in a known dotfile, I would however suggest adding an option to `install` so that you can force, as part of installing a dotfile, remove any other files present. What do you think?

**Comment by lictw** [comment]
Yep, I thinks it's nice!

**Comment by deadc0de6** [comment]
Ok cool, I'll work on this and keep you posted

**Comment by deadc0de6** [comment]
@lictw the two branches have been merged into master. Both features are now available:

* new `uninstall` command to uninstall files installed by dotdrop
* new `install` command line switch `--remove-existing` to remove any files not managed by dotdrop
