### ISSUE TITLE
Hidden directory breaks compare

### ISSUE THREAD

**Issue by medman826** [deadc0de6/dotdrop#5]
It seems as though dotdrop compare crashes if you try to use dotdrop to manage a hidden directory.

```
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.2
                               |_|

diffing "f_zshrc" VS "~/.zshrc"
same file
diffing "f_xresources" VS "~/.Xresources"
same file
diffing "f_xmodmap" VS "~/.Xmodmap"
same file
diffing "f_xinitrc" VS "~/.xinitrc"
same file
diffing "f_xbindkeysrc" VS "~/.xbindkeysrc"
same file
diffing "f_vimrc" VS "~/.vimrc"
same file
diffing "f_i3blocks.conf" VS "~/.i3blocks.conf"
70c70
< instance=/mSATA
---
> instance=/media/mSATA
diffing "f_conkyrc" VS "~/.conkyrc"
same file
diffing "f_compton.conf" VS "~/.config/compton.conf"
same file
diffing "d_i3" VS "~/.i3"
Traceback (most recent call last):
  File "/home/matthew/dotfiles/dotdrop/dotdrop/dotdrop.py", line 182, in <module>
    if compare(opts, conf, tmp):
  File "/home/matthew/dotfiles/dotdrop/dotdrop/dotdrop.py", line 91, in compare
    inst.compare(t, tmp, opts['profile'], dotfile.src, dotfile.dst)
  File "/home/matthew/dotfiles/dotdrop/dotdrop/installer.py", line 168, in compare
    tmpfolder)
  File "/home/matthew/dotfiles/dotdrop/dotdrop/installer.py", line 151, in _install_to_temp
    return self.install(templater, profile, src, tmpdst), tmpdst
  File "/home/matthew/dotfiles/dotdrop/dotdrop/installer.py", line 32, in install
    return self._handle_dir(templater, profile, src, dst)
  File "/home/matthew/dotfiles/dotdrop/dotdrop/installer.py", line 91, in _handle_dir
    templater, profile, f, os.path.join(dst, entry))
  File "/home/matthew/dotfiles/dotdrop/dotdrop/installer.py", line 66, in _handle_file
    content = templater.generate(src, profile)
  File "/home/matthew/dotfiles/dotdrop/dotdrop/templategen.py", line 35, in generate
    return self._handle_file(src, profile)
  File "/home/matthew/dotfiles/dotdrop/dotdrop/templategen.py", line 42, in _handle_file
    return self._handle_bin_file(src, profile)
  File "/home/matthew/dotfiles/dotdrop/dotdrop/templategen.py", line 62, in _handle_bin_file
    with open(src, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/matthew/dotfiles/dotfiles/i3/.i3'
```

**Comment by medman826** [comment]
Turns out the problem was that I had a symlink to something that no longer existed in ~/dotfiles/dotfiles/i3/, and that was causing the program to break when attempting to open it.

**Comment by deadc0de6** [comment]
Thanks for reporting this.
I have added some checks such that an error is printed instead of a crash.

**Comment by deadc0de6** [comment]
I'm adding some repositories as examples in the readme, would you be ok if I add yours as a reference ?

**Comment by medman826** [comment]
It has been awhile since I managed my dotfiles with dotdrop. Since I last
attempted to use it, I built a new computer that requires a unique dotfiles
configuration. Give me a bit to create a good dotdrop example that works
well between my two systems and I'd be happy for you to use it as an
example.

**Comment by deadc0de6** [comment]
sure, no problem. Let me know when you're good and I'll add yours.

thanks

**Comment by medman826** [comment]
I'm realizing that your code doesn't work on macs. I was hoping to set it
up with my mac, my home pc w/ linux, and my linux laptop.

**Comment by deadc0de6** [comment]
could you be more specific, what is not working ? the hidden directory compare ?

**Comment by mdiamond** [comment]
I don't think the hidden directory compare is a problem anymore. But there
are a number of things broken. First it crashed because python3 is not in
the path by default, you have to specifically install it using homebrew,
the unofficial mac os package manager. Then, I had issues with docopt not
being installed, which resulted in me having to easy_install pip, then pip
install docopt. And finally, now, even after doing pip install docopt,
dotdrop.sh crashed saying "No module named 'docopt'". I don't know what
else might be wrong because I've given up lol.

Do you hope to get dotdrop working on mac? I would be open to helping when
I have free time.

Matthew

**Comment by deadc0de6** [comment]
Of course you need to have python3 to run dotdrop. Regarding the `docopt` dependency (as well as other dependencies), you can easily install it with pip: `sudo pip3 install -r dotdrop/requirements.txt`.

Are you sure you installed the python3 version of docopt ? Since it seems mac has python2 per default so invoking pip with `pip` might call the python2 version. At least on some linux distribution (ubuntu/debian), you need to explicitly call `pip3` in order to install python3 versions of libraries. To test that you could simply run a python shell (usually by simply running `python3` at the command line) and then issuing `import docopt`. 

I don't use mac so it's difficult to test but let me know how the above works out.
