### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by mygithubthrowaway** [deadc0de6/dotdrop#98]
Hi there,

I just installed from aur, created .dotdrop dir and export env:

`   DOTREPO="$HOME/.dotdrop"`

than created a empty ~/.dotdrop/config.yaml like this:

```
config:
        backup: True
        create: True
dotfiles:

profiles:
        test:
```

`dotdrop import ~/.xinitrc `
```

Traceback (most recent call last):
  File "/usr/bin/dotdrop", line 11, in <module>
    load_entry_point('dotdrop==0.25.2', 'console_scripts', 'dotdrop')()
  File "/usr/lib/python3.7/site-packages/dotdrop/__init__.py", line 11, in main
    if dotdrop.dotdrop.main():
  File "/usr/lib/python3.7/site-packages/dotdrop/dotdrop.py", line 380, in main
    o = Options()
  File "/usr/lib/python3.7/site-packages/dotdrop/options.py", line 99, in __init__
    self._read_config()
  File "/usr/lib/python3.7/site-packages/dotdrop/options.py", line 117, in _read_config
    self.conf = Cfg(self.confpath, debug=self.debug)
  File "/usr/lib/python3.7/site-packages/dotdrop/config.py", line 123, in __init__
    if not self._load_file():
  File "/usr/lib/python3.7/site-packages/dotdrop/config.py", line 150, in _load_file
    return self._parse()
  File "/usr/lib/python3.7/site-packages/dotdrop/config.py", line 206, in _parse
    if self.key_profiles_dots in v and \
TypeError: argument of type 'NoneType' is not iterable
```

if i remove "dotfiles:" from config.yaml:
```

dotdrop import ~/.xinitrc 
[ERR] missing "dotfiles" in config 
[ERR] Config format error: config is not valid 
```

Thanks!

**Comment by deadc0de6** [comment]
Thanks for reporting this. 

Actually `DOTREPO` is not an available environment variable understood by dotdrop. The entry `dotpath` under the `config` entry needs to be defined in the config file or it will get the default value (`dotfiles`).

There still was a bug due to the fact you manually declared a profile without any dotfiles. This is now fixed.

The config file has three mandatory fields which are `config`, `dotfiles` and `profiles`. I updated [the doc](https://github.com/deadc0de6/dotdrop#config) to make sure this is clear.

**Comment by deadc0de6** [comment]
The documentation was moved to the [wiki](https://github.com/deadc0de6/dotdrop/wiki). Here's the doc for the config format: <https://github.com/deadc0de6/dotdrop/wiki/config#format>.

Let me know if you're having any other issues, thanks!

**Comment by mygithubthrowaway** [comment]
Yep, i'am sorry for late reply, now work as expected.

Nice step to move documentation to wiki, thanks again :)
